# GraphIQ - schemas.py
# Pydantic models for API request/response validation.

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Request body for the chat endpoint."""
    query: str = Field(..., min_length=1, description="The user's natural-language question.")


class ChatResponse(BaseModel):
    """Response body from the chat endpoint."""
    answer: str = Field(..., description="The human-readable answer generated by the LLM.")
    cypher: str = Field(default="", description="The Cypher query that was executed.")
    raw_results: list = Field(default_factory=list, description="Raw query results from Neo4j.")
    allowed: bool = Field(default=True, description="Whether the query passed the guardrail check.")


class GraphResponse(BaseModel):
    """Response body for the graph export endpoint."""
    nodes: list = Field(default_factory=list, description="List of graph nodes in Cytoscape.js format.")
    edges: list = Field(default_factory=list, description="List of graph edges in Cytoscape.js format.")


class HealthResponse(BaseModel):
    """Response body for the health check endpoint."""
    status: str = Field(..., description="Application health status.")
    neo4j_connected: bool = Field(..., description="Whether Neo4j is reachable.")
